export default {
    LABEL: 1,
    INPUT: 2,
    NUMBER: 2 << 1,
    DROPDOWN: 2 << 2,
    IMAGE: 2 << 3,
    ORIGINSIZE: 2 << 4,
    TEXTAREA: 2 << 5,
    SPLITER: 2 << 6,
    BOOLEAN: 2 << 7,
    LINEHEIGHT: 2 << 8,
    FONTSTYLE: 2 << 9,
    FONTALIGN: 2 << 10,
    CELLOPERATE: 2 << 11,
    CELLSIZE: 2 << 12,
    CELLFOCUS: 2 << 13,
    CELLCOLSHARE: 2 << 14,
    CELLROWSHARE: 2 << 15,
    CELLDROPDOWN: 2 << 16
};